/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.edd_proyecto_final.ui;

import javax.swing.JInternalFrame;

/**
 *
 * @author Temporal
 */
public class Desktop extends javax.swing.JFrame {

    /**
     * Creates new form Desktop
     */
    public Desktop() {
        initComponents();
        setLocationRelativeTo(null);
        menuBar.setVisible(false);
        Login login = new Login(menuBar);
        login.setSize(250, 400);
        
        login.setLocation(desktopPane.getWidth()/2-125, desktopPane.getHeight()/2-200);
        login.setVisible(true);
        desktopPane.repaint();
        desktopPane.add(login);
        desktopPane.revalidate();
        
//        this.repaint();
//        this.revalidate();
//        this.add(login);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        btnFile = new javax.swing.JMenu();
        btnCargar = new javax.swing.JMenuItem();
        btnSave = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        btnCrear = new javax.swing.JMenu();
        crearEstudiante = new javax.swing.JMenuItem();
        crearCatedratico = new javax.swing.JMenuItem();
        crearHorario = new javax.swing.JMenuItem();
        aboutMenuItem3 = new javax.swing.JMenuItem();
        aboutMenuItem5 = new javax.swing.JMenuItem();
        aboutMenuItem6 = new javax.swing.JMenuItem();
        aboutMenuItem7 = new javax.swing.JMenuItem();
        btnEditar = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem4 = new javax.swing.JMenuItem();
        aboutMenuItem8 = new javax.swing.JMenuItem();
        btnGraficar = new javax.swing.JMenu();
        contentMenuItem2 = new javax.swing.JMenuItem();
        aboutMenuItem9 = new javax.swing.JMenuItem();
        aboutMenuItem10 = new javax.swing.JMenuItem();
        aboutMenuItem11 = new javax.swing.JMenuItem();
        aboutMenuItem12 = new javax.swing.JMenuItem();
        aboutMenuItem13 = new javax.swing.JMenuItem();
        aboutMenuItem14 = new javax.swing.JMenuItem();
        btnAcerca = new javax.swing.JMenu();
        contentMenuItem1 = new javax.swing.JMenuItem();
        aboutMenuItem1 = new javax.swing.JMenuItem();
        btnSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnFile.setMnemonic('f');
        btnFile.setText("Archivo");

        btnCargar.setMnemonic('o');
        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        btnFile.add(btnCargar);

        btnSave.setMnemonic('s');
        btnSave.setText("Guardar");
        btnFile.add(btnSave);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        btnFile.add(exitMenuItem);

        menuBar.add(btnFile);

        btnCrear.setMnemonic('h');
        btnCrear.setText("Crear");

        crearEstudiante.setMnemonic('c');
        crearEstudiante.setText("Estudiante");
        btnCrear.add(crearEstudiante);

        crearCatedratico.setMnemonic('a');
        crearCatedratico.setText("Catedratico");
        btnCrear.add(crearCatedratico);

        crearHorario.setMnemonic('a');
        crearHorario.setText("Horario");
        btnCrear.add(crearHorario);

        aboutMenuItem3.setMnemonic('a');
        aboutMenuItem3.setText("Curso");
        btnCrear.add(aboutMenuItem3);

        aboutMenuItem5.setMnemonic('a');
        aboutMenuItem5.setText("Usuario");
        btnCrear.add(aboutMenuItem5);

        aboutMenuItem6.setMnemonic('a');
        aboutMenuItem6.setText("Edificio");
        btnCrear.add(aboutMenuItem6);

        aboutMenuItem7.setMnemonic('a');
        aboutMenuItem7.setText("Asignacion");
        btnCrear.add(aboutMenuItem7);

        menuBar.add(btnCrear);

        btnEditar.setMnemonic('e');
        btnEditar.setText("Editar");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Estudiante");
        btnEditar.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Catedratico");
        btnEditar.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Horario");
        btnEditar.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Curso");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        btnEditar.add(deleteMenuItem);

        aboutMenuItem4.setMnemonic('a');
        aboutMenuItem4.setText("Catedratico");
        btnEditar.add(aboutMenuItem4);

        aboutMenuItem8.setMnemonic('a');
        aboutMenuItem8.setText("Asignacion");
        btnEditar.add(aboutMenuItem8);

        menuBar.add(btnEditar);

        btnGraficar.setMnemonic('h');
        btnGraficar.setText("Graficar");

        contentMenuItem2.setMnemonic('c');
        contentMenuItem2.setText("Estudiante");
        btnGraficar.add(contentMenuItem2);

        aboutMenuItem9.setMnemonic('a');
        aboutMenuItem9.setText("Catedratico");
        btnGraficar.add(aboutMenuItem9);

        aboutMenuItem10.setMnemonic('a');
        aboutMenuItem10.setText("Horario");
        btnGraficar.add(aboutMenuItem10);

        aboutMenuItem11.setMnemonic('a');
        aboutMenuItem11.setText("Curso");
        btnGraficar.add(aboutMenuItem11);

        aboutMenuItem12.setMnemonic('a');
        aboutMenuItem12.setText("Usuario");
        btnGraficar.add(aboutMenuItem12);

        aboutMenuItem13.setMnemonic('a');
        aboutMenuItem13.setText("Edificio");
        btnGraficar.add(aboutMenuItem13);

        aboutMenuItem14.setMnemonic('a');
        aboutMenuItem14.setText("Asignacion");
        btnGraficar.add(aboutMenuItem14);

        menuBar.add(btnGraficar);

        btnAcerca.setMnemonic('h');
        btnAcerca.setText("Acerca De");

        contentMenuItem1.setMnemonic('c');
        contentMenuItem1.setText("Contents");
        btnAcerca.add(contentMenuItem1);

        aboutMenuItem1.setMnemonic('a');
        aboutMenuItem1.setText("About");
        btnAcerca.add(aboutMenuItem1);

        menuBar.add(btnAcerca);

        btnSalir.setMnemonic('e');
        btnSalir.setText("Salir");
        menuBar.add(btnSalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1004, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        //System.exit(0);
        
        agregarInternal(new Login(menuBar));
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
            LoadFile file = new LoadFile();
            agregarInternal(file);
    }//GEN-LAST:event_btnCargarActionPerformed

    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMenuItemActionPerformed

    public void agregarInternal(JInternalFrame internal){
        internal.setSize(desktopPane.getSize());
        internal.setVisible(true);
        desktopPane.removeAll();
        desktopPane.repaint();
        desktopPane.add(internal);
        desktopPane.repaint();
        desktopPane.revalidate();
                
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem1;
    private javax.swing.JMenuItem aboutMenuItem10;
    private javax.swing.JMenuItem aboutMenuItem11;
    private javax.swing.JMenuItem aboutMenuItem12;
    private javax.swing.JMenuItem aboutMenuItem13;
    private javax.swing.JMenuItem aboutMenuItem14;
    private javax.swing.JMenuItem aboutMenuItem3;
    private javax.swing.JMenuItem aboutMenuItem4;
    private javax.swing.JMenuItem aboutMenuItem5;
    private javax.swing.JMenuItem aboutMenuItem6;
    private javax.swing.JMenuItem aboutMenuItem7;
    private javax.swing.JMenuItem aboutMenuItem8;
    private javax.swing.JMenuItem aboutMenuItem9;
    private javax.swing.JMenu btnAcerca;
    private javax.swing.JMenuItem btnCargar;
    private javax.swing.JMenu btnCrear;
    private javax.swing.JMenu btnEditar;
    private javax.swing.JMenu btnFile;
    private javax.swing.JMenu btnGraficar;
    private javax.swing.JMenu btnSalir;
    private javax.swing.JMenuItem btnSave;
    private javax.swing.JMenuItem contentMenuItem1;
    private javax.swing.JMenuItem contentMenuItem2;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem crearCatedratico;
    private javax.swing.JMenuItem crearEstudiante;
    private javax.swing.JMenuItem crearHorario;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables

}
